/* ====================================================================
   ATÍPICOS FRIOS — produtos.js
   Estrutura de dados dos produtos da loja.
   Cada produto: id, nome, categoria, descricao, preco, precoAntigo,
   unidade, imagem, novo, oferta, destaque, disponivel.
   ==================================================================== */

const PRODUTOS = [
  {
    id: 1,
    nome: "Queijo Coalho Geason Diniz",
    categoria: "Churrasco",
    descricao: "Assa com sal, direto na chapa ou churrasqueira.",
    preco: 23.00,
    precoAntigo: null,
    unidade: "barra",
    imagem: "images/queijo_coalho.png",
    novo: false,
    oferta: true,
    destaque: true,
    disponivel: true
  },
  {
    id: 2,
    nome: "Kit Churrasco Geason Diniz",
    categoria: "Churrasco",
    descricao: "Linguiça gourmet, queijo coalho e farofa gourmet.",
    preco: null,
    precoAntigo: null,
    unidade: "kit completo",
    imagem: "images/kit_churrasco.png",
    novo: false,
    oferta: true,
    destaque: true,
    disponivel: true
  },
  {
    id: 3,
    nome: "Linguiça Gourmet",
    categoria: "Frios",
    descricao: "De bode e outras opções gourmet, direto da churrasqueira.",
    preco: null,
    precoAntigo: null,
    unidade: "un.",
    imagem: "images/kit_churrasco.png",
    novo: false,
    oferta: false,
    destaque: false,
    disponivel: true
  },
  {
    id: 4,
    nome: "Frios em Bandeja",
    categoria: "Frios",
    descricao: "Seleção de frios fatiados, prontos para servir.",
    preco: 10.00,
    precoAntigo: null,
    unidade: "bandeja",
    imagem: "images/frios_bandeja.png",
    novo: false,
    oferta: false,
    destaque: false,
    disponivel: true
  },
  {
    id: 5,
    nome: "Bandeja de Frios do Dia",
    categoria: "Frios",
    descricao: "R$10,00 a bandeja — confira o que chegou hoje.",
    preco: 10.00,
    precoAntigo: null,
    unidade: "bandeja",
    imagem: "images/frios_bandeja.png",
    novo: false,
    oferta: true,
    destaque: false,
    disponivel: true
  },
  {
    id: 6,
    nome: "Bandejas de Frios Sortidos",
    categoria: "Frios",
    descricao: "Variedade que encanta, com frescor garantido todo dia.",
    preco: null,
    precoAntigo: null,
    unidade: "bandeja",
    imagem: "images/frios_bandeja.png",
    novo: true,
    oferta: false,
    destaque: false,
    disponivel: true
  },
  {
    id: 7,
    nome: "Morangos Congelados Dona Horta",
    categoria: "Congelados",
    descricao: "Ideais para açaí, vitaminas e sobremesas.",
    preco: 10.00,
    precoAntigo: null,
    unidade: "un. · 5 un. por R$47,50",
    imagem: "images/morangos.png",
    novo: false,
    oferta: true,
    destaque: false,
    disponivel: true
  },
  {
    id: 8,
    nome: "Filé de Peito Jussara",
    categoria: "Congelados",
    descricao: "Congelado individualmente (IQF), pronto para usar 1 a 1.",
    preco: null,
    precoAntigo: null,
    unidade: "un. (IQF)",
    imagem: "images/file_peito.png",
    novo: false,
    oferta: true,
    destaque: true,
    disponivel: true
  },
  {
    id: 9,
    nome: "Bebidas Itambé & Fruty Bom",
    categoria: "Bebidas",
    descricao: "Coco, uva e sabores selecionados.",
    preco: 10.00,
    precoAntigo: null,
    unidade: "un.",
    imagem: "images/oferta_dia.png",
    novo: false,
    oferta: true,
    destaque: false,
    disponivel: true
  },
  {
    id: 10,
    nome: "Molho Pronto Italac",
    categoria: "Mercearia",
    descricao: "4 queijos ou branco, prático e saboroso.",
    preco: 4.00,
    precoAntigo: null,
    unidade: "un. · 3 un. por R$10",
    imagem: "images/molho_italac.png",
    novo: false,
    oferta: true,
    destaque: false,
    disponivel: true
  },
  {
    id: 11,
    nome: "Biscoito Marilan Manteiga",
    categoria: "Mercearia",
    descricao: "Aquele clássico para o café da tarde.",
    preco: null,
    precoAntigo: null,
    unidade: "pacote · 3 por R$10",
    imagem: "images/biscoito_marilan.png",
    novo: false,
    oferta: true,
    destaque: false,
    disponivel: true
  },
  {
    id: 12,
    nome: "3 Bandejas Natural Gurt",
    categoria: "Sobremesas",
    descricao: "Sabor morango, cremoso e geladinho.",
    preco: 10.00,
    precoAntigo: null,
    unidade: "as 3 bandejas",
    imagem: "images/natural_gurt.png",
    novo: false,
    oferta: true,
    destaque: false,
    disponivel: true
  },
  {
    id: 13,
    nome: "Açaí Cremoso e Natural",
    categoria: "Sobremesas",
    descricao: "100% natural, perfeito para refrescar o dia e dividir com a família.",
    preco: null,
    precoAntigo: null,
    unidade: "cuba",
    imagem: "images/acai.png",
    novo: true,
    oferta: false,
    destaque: false,
    disponivel: true
  }
];
